export const GET_ALL_JOB_REQUEST = "GET_ALL_JOB_REQUEST";
export const GET_ALL_JOB_SUCCESS = "GET_ALL_JOB_SUCCESS";
export const GET_ALL_JOB_FAIL = "GET_ALL_JOB_FAIL";

export const GET_SINGLE_JOB_REQUEST = "GET_SINGLE_JOB_REQUEST";
export const GET_SINGLE_JOB_SUCCESS = "GET_SINGLE_JOB_SUCCESS";
export const GET_SINGLE_JOB_FAIL = "GET_SINGLE_JOB_FAIL";

export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL";

export const SEND_APPLICANT_EMAIL_REQUEST = "SEND_APPLICANT_EMAIL_REQUEST";
export const SEND_APPLICANT_EMAIL_SUCCESS = "SEND_APPLICANT_EMAIL_SUCCESS";
export const SEND_APPLICANT_EMAIL_FAIL = "SEND_APPLICANT_EMAIL_FAIL";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";
