export const GET_MY_POST_REQUEST = "GET_MY_POST_REQUEST";
export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS";
export const GET_MY_POST_FAIL = "GET_MY_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAIL = "GET_ALL_POST_FAIL";

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL";
export const GET_SINGLE_POST_RESET = "GET_SINGLE_POST_RESET";

export const POST_LIKE_AND_UNLIKE_REQUEST = "POST_LIKE_AND_UNLIKE_REQUEST";
export const POST_LIKE_AND_UNLIKE_SUCCESS = "POST_LIKE_AND_UNLIKE_SUCCESS";
export const POST_LIKE_AND_UNLIKE_FAIL = "POST_LIKE_AND_UNLIKE_FAIL";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const LIKE_AND_UNLIKE_COMMENT_REQUEST =
  "LIKE_AND_UNLIKE_COMMENT_REQUEST";
export const LIKE_AND_UNLIKE_COMMENT_SUCCESS =
  "LIKE_AND_UNLIKE_COMMENT_SUCCESS";
export const LIKE_AND_UNLIKE_COMMENT_FAIL = "LIKE_AND_UNLIKE_COMMENT_FAIL";

export const ADD_REPLY_REQUEST = "ADD_REPLY_REQUEST";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_FAIL = "ADD_REPLY_FAIL";

export const DELETE_REPLY_REQUEST = "DELETE_REPLY_REQUEST";
export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_FAIL = "DELETE_REPLY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
