export const GET_ALL_QUESTIONS_REQUEST = "GET_ALL_QUESTIONS_REQUEST";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS";
export const GET_ALL_QUESTIONS_FAIL = "GET_ALL_QUESTIONS_FAIL";

export const CREATE_QUESTIONS_REQUEST = "CREATE_QUESTIONS_REQUEST";
export const CREATE_QUESTIONS_SUCCESS = "CREATE_QUESTIONS_SUCCESS";
export const CREATE_QUESTIONS_FAIL = "CREATE_QUESTIONS_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";

export const GET_SINGLE_QUESTION_REQUEST = "GET_SINGLE_QUESTION_REQUEST";
export const GET_SINGLE_QUESTION_SUCCESS = "GET_SINGLE_QUESTION_SUCCESS";
export const GET_SINGLE_QUESTION_FAIL = "GET_SINGLE_QUESTION_FAIL";

export const GET_LIKEANDUNLIKE_QUESTION_REQUEST =
  "GET_LIKEANDUNLIKE_QUESTION_REQUEST";
export const GET_LIKEANDUNLIKE_QUESTION_SUCCESS =
  "GET_LIKEANDUNLIKE_QUESTION_SUCCESS";
export const GET_LIKEANDUNLIKE_QUESTION_FAIL =
  "GET_LIKEANDUNLIKE_QUESTION_FAIL";

export const VIEW_QUESTION_REQUEST = "VIEW_QUESTION_REQUEST";
export const VIEW_QUESTION_SUCCESS = "VIEW_QUESTION_SUCCESS";
export const VIEW_QUESTION_FAIL = "VIEW_QUESTION_FAIL";

export const CREATE_ANSWER_REQUEST = "CREATE_ANSWER_REQUEST";
export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAIL = "CREATE_ANSWER_FAIL";

export const UPDATE_ANSWER_REQUEST = "UPDATE_ANSWER_REQUEST";
export const UPDATE_ANSWER_SUCCESS = "UPDATE_ANSWER_SUCCESS";
export const UPDATE_ANSWER_FAIL = "UPDATER_FAIL";

export const DELETE_ANSWER_REQUEST = "DELETE_ANSWER_REQUEST";
export const DELETE_ANSWER_SUCCESS = "DELETE_ANSWER_SUCCESS";
export const DELETE_ANSWER_FAIL = "DELETE_ANSWER_FAIL";

export const LIKE_ANSWER_REQUEST = "LIKE_ANSWER_REQUEST";
export const LIKE_ANSWER_SUCCESS = "LIKE_ANSWER_SUCCESS";
export const LIKE_ANSWER_FAIL = "LIKE_ANSWER_FAIL";
