export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_RESET = "UPDATE_AVATAR_RESET";
export const UPDATE_AVATAR_FAIL = "UPDATE_AVATAR_FAIL";

export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_RESET = "UPDATE_BANNER_RESET";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";

export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS";
export const UPDATE_ABOUT_RESET = "UPDATE_ABOUT_RESET";
export const UPDATE_ABOUT_FAIL = "UPDATE_ABOUT_FAIL";

export const UPDATE_SKILL_REQUEST = "UPDATE_SKILL_REQUEST";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
export const UPDATE_SKILL_RESET = "UPDATE_SKILL_RESET";
export const UPDATE_SKILL_FAIL = "UPDATE_SKILL_FAIL";

export const DELETE_SKILL_REQUEST = "DELETE_SKILL_REQUEST";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_FAIL = "DELETE_SKILL_FAIL";
export const DELETE_SKILL_RESET = "DELETE_SKILL_RESET";

export const UPDATE_EXPERIENCE_REQUEST = "UPDATE_EXPERIENCE_REQUEST";
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS";
export const UPDATE_EXPERIENCE_RESET = "UPDATE_EXPERIENCE_RESET";
export const UPDATE_EXPERIENCE_FAIL = "UPDATE_EXPERIENCE_FAIL";

export const DELETE_EXPERIENCE_REQUEST = "DELETE_EXPERIENCE_REQUEST";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAIL = "DELETE_EXPERIENCE_FAIL";
export const DELETE_EXPERIENCE_RESET = "DELETE_EXPERIENCE_RESET";

export const UPDATE_EDUCATION_REQUEST = "UPDATE_EDUCATION_REQUEST";
export const UPDATE_EDUCATION_SUCCESS = "UPDATE_EDUCATION_SUCCESS";
export const UPDATE_EDUCATION_RESET = "UPDATE_EDUCATION_RESET";
export const UPDATE_EDUCATION_FAIL = "UPDATE_EDUCATION_FAIL";

export const DELETE_EDUCATION_REQUEST = "DELETE_EDUCATION_REQUEST";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAIL = "DELETE_EDUCATION_FAIL";
export const DELETE_EDUCATION_RESET = "DELETE_EDUCATION_RESET";

export const UPDATE_PORTFOLIO_REQUEST = "UPDATE_PORTFOLIO_REQUEST";
export const UPDATE_PORTFOLIO_SUCCESS = "UPDATE_PORTFOLIO_SUCCESS";
export const UPDATE_PORTFOLIO_RESET = "UPDATE_PORTFOLIO_RESET";
export const UPDATE_PORTFOLIO_FAIL = "UPDATE_PORTFOLIO_FAIL";

export const DELETE_PORTFOLIO_REQUEST = "DELETE_PORTFOLIO_REQUEST";
export const DELETE_PORTFOLIO_SUCCESS = "DELETE_PORTFOLIO_SUCCESS";
export const DELETE_PORTFOLIO_FAIL = "DELETE_PORTFOLIO_FAIL";
export const DELETE_PORTFOLIO_RESET = "DELETE_PORTFOLIO_RESET";

export const UPDATE_LANGUAGE_REQUEST = "UPDATE_LANGUAGE_REQUEST";
export const UPDATE_LANGUAGE_SUCCESS = "UPDATE_LANGUAGE_SUCCESS";
export const UPDATE_LANGUAGE_RESET = "UPDATE_LANGUAGE_RESET";
export const UPDATE_LANGUAGE_FAIL = "UPDATE_LANGUAGE_FAIL";

export const DELETE_LANGUAGE_REQUEST = "DELETE_LANGUAGE_REQUEST";
export const DELETE_LANGUAGE_SUCCESS = "DELETE_LANGUAGE_SUCCESS";
export const DELETE_LANGUAGE_FAIL = "DELETE_LANGUAGE_FAIL";
export const DELETE_LANGUAGE_RESET = "DELETE_LANGUAGE_RESET";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const ALL_DEVELOPER_REQUEST = "ALL_DEVELOPER_REQUEST";
export const ALL_DEVELOPER_SUCCESS = "ALL_DEVELOPER_SUCCESS";
export const ALL_DEVELOPER_FAIL = "ALL_DEVELOPER_FAIL";

export const SINGLE_DEVELOPER_REQUEST = "SINGLE_DEVELOPER_REQUEST";
export const SINGLE_DEVELOPER_SUCCESS = "SINGLE_DEVELOPER_SUCCESS";
export const SINGLE_DEVELOPER_FAIL = "SINGLE_DEVELOPER_FAIL";

export const ADMIN_USER_REQUEST = "ADMIN_USER_REQUEST";
export const ADMIN_USER_SUCCESS = "ADMIN_USER_SUCCESS";
export const ADMIN_USER_FAIL = "ADMIN_USER_FAIL";

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
